---
- name: Share IP through mnt
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Set IP address to mnt
      ansible.builtin.shell:
        cmd: |
          ip -4 addr show enp0s8 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' > /mnt/$(hostname).txt
