- name: Create and Populate Database
  hosts: localhost
  become: true

  tasks:
    - name: Set PostgreSQL user password
      ansible.builtin.shell:
        cmd: sudo -iu postgres psql -c "ALTER USER postgres PASSWORD '123456';"

    - name: Create database
      ansible.builtin.shell:
        cmd: sudo -iu postgres createdb mydatabase

    - name: Create cities table
      ansible.builtin.shell:
        cmd: |
          sudo -iu postgres psql -d mydatabase -c "CREATE TABLE cities (
            id SERIAL PRIMARY KEY,
            city VARCHAR(255) NOT NULL,
            country VARCHAR(255) NOT NULL,
            population BIGINT NOT NULL
          );"

    - name: Insert data into cities table
      ansible.builtin.shell:
        cmd: |
          sudo -iu postgres psql -d mydatabase -c "INSERT INTO public.cities (city, country, population) VALUES
            ('Tokyo', 'Japan', 37400068),
            ('Delhi', 'India', 28514000),
            ('Shanghai', 'China', 25582000),
            ('São Paulo', 'Brazil', 22046000),
            ('Mexico City', 'Mexico', 21672000),
            ('Cairo', 'Egypt', 20484900),
            ('Dhaka', 'Bangladesh', 20278000),
            ('Mumbai', 'India', 20185000),
            ('Beijing', 'China', 20035455),
            ('Karachi', 'Pakistan', 16093786),
            ('Chongqing', 'China', 15872000),
            ('Istanbul', 'Turkey', 15460000),
            ('Buenos Aires', 'Argentina', 14967000),
            ('Kolkata', 'India', 14865000),
            ('Lagos', 'Nigeria', 14767800),
            ('Manila', 'Philippines', 13923452),
            ('Rio de Janeiro', 'Brazil', 13636000),
            ('Lahore', 'Pakistan', 13052300),
            ('Bangalore', 'India', 12736292),
            ('London', 'United Kingdom', 12500000);"
