---
- name: Clone Playbooks
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Move playbooks foæder to home directory
      command: mv ~/FlaskWebApp/playbooks/ ~/

    - name: Remove the cloned FlaskWebApp directory
      file:
        path: ~/FlaskWebApp
        state: absent
