- name: Git Project Setup
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Create folder playbooks/
      file:
        path: "/home/ubuntu/playbooks"
        state: directory

    - name: Copy the cloned project to playbooks/
      copy:
        src: "/home/ubuntu/FlaskWebApp/"
        dest: "/home/ubuntu/playbooks/"
        remote_src: yes

    - name: Remove FlaskWebApp directory
      file:
        path: "/home/ubuntu/FlaskWebApp"
        state: absent

    - name: Additional operations on the playbooks directory
      debug:
        msg: "Perform operations here, ensuring /home/ubuntu/FlaskWebApp is no longer referenced."
