---
- name: Git Project Setup
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Create folder playbooks/
      file:
        path: /playbooks/
        state: directory

    - name: Copy the cloned project to /var/www
      ansible.builtin.copy:
        src: ~/FlaskWebApp/
        dest: /playbooks/
        owner: root
        group: root

    - name: Remove FlaskWebApp directory
      file:
        path: ~/FlaskWebApp
        state: absent
