---
- name: Git Project Setup
  hosts: localhost
  become: true
  tasks:
    - name: Create the folder playbooks/
      file:
        path: /home/ubuntu/playbooks/
        state: directory

    - name: Copy the cloned project to playbooks/
      ansible.builtin.copy:
        src: /home/ubuntu/FlaskWebApp/
        dest: /home/ubuntu/playbooks/
        owner: ubuntu
        group: ubuntu
