---
- name: Git Project Setup
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Remove existing files from /var/www
      file:
        path: /var/www/
        state: absent

    - name: Create new /var/www
      file:
        path: /var/www/
        state: directory

    - name: Copy the cloned project to /var/www
      ansible.builtin.copy:
        src: ~/FlaskWebApp/
        dest: /var/www/
        owner: root
        group: root

    - name: Remove FlaskWebApp directory
      file:
        path: ~/FlaskWebApp
        state: absent

    # PERMISSIONS
    - name: Change ownership of subdirectories to 'ubuntu'
      file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes
      with_items:
        - /var/www/flask

    - name: Set directory permissions for html and project directories
      file:
        path: "{{ item }}"
        mode: "0755"
        recurse: yes
      with_items:
        - /var/www/html
        - /var/www/flask/project

    - name: Set file permissions for html, static files, and templates
      find:
        paths: "{{ item }}"
        file_type: file
        recurse: yes
      register: files_to_modify
      with_items:
        - /var/www/html
        - /var/www/flask/project/static
        - /var/www/flask/project/templates

    - name: Apply file permissions to discovered files
      file:
        path: "{{ item.path }}"
        mode: "0644"
      with_items: "{{ files_to_modify.results | map(attribute='files') | flatten }}"

    - name: Set permissions for flask main directory and scripts
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: "/var/www/flask", mode: "0750" }
        - { path: "/var/www/flask/app.py", mode: "0750" }
        - { path: "/var/www/flask/project/__init__.py", mode: "0640" }
